### ISSUE TITLE
No keyboard input in terminal

### ISSUE THREAD

**Issue by bortels** [felixgborrego/docker-ui-chrome-app#1]
The terminal seems to be flakey - the first container I ran (bortels/rubydev which is my generic ruby dev environment) showed the irb prompt, but no keyboard input worked. Killing that and starting again just shows [Connected], without the prompt or keyboard working. Tried a few different variants, down to something as simple as busybox. Killed it, restarted, same behavior (no prompt at all in the terminal). 

Environment: OS X Yoemite, boot2docker 1.4.1, docker client version 5. Upgrading to boot2docker 1.5 has the same issue. 

PS. This looks really really nice. Thank you for sharing.

**Comment by felixgborrego** [comment]
Thanks for your feedback. 
You are right there are several improvement I had to add to the terminal. 
The terminal auto attaches to the default stdin/stdout/tty of the container and this usually doesn't have stdin enabled. There are several things I'm planing to do here:
- Show in the UI when there is not stdin connected for terminal.
- Allow attach new bash ( Equivalent to `docker exec -it 1a561e16f66a  bash` )
- When creating a new container from the UI, allow the user to attach stdin and stdout.

**Comment by felixgborrego** [comment]
Fixed and published. There are still minor issues related with term.js but stdin and stout is working.
