### ISSUE TITLE
incorrect summarized size for containers and images

### ISSUE THREAD

**Issue by asziranyi** [felixgborrego/docker-ui-chrome-app#12]
There is incorrect size for sum of containers and images in case of many big containers and images. Perhaps this is only an Integer overflow? Suggestion is to convert the summarized size to MB, GB, TB based on size.

![incorrect_size](https://cloud.githubusercontent.com/assets/3259948/9016545/33a6eaf4-37d2-11e5-8326-6ac7f1f9004d.png)

**Comment by felixgborrego** [comment]
It's an integer overflow, last time I look into this issue I run into an odd scalajs/upickle issue while parsing the json from Docker Remote API but maybe there is a work around.
