### ISSUE TITLE
Any chance of adding Volume mapping

### ISSUE THREAD

**Issue by tom472** [felixgborrego/docker-ui-chrome-app#13]
I have been testing your Docker UI Chrome app and have been really impressed with it.
One item I was looking for that I did not see was a place to add / do volume mapping when starting up a container.
Is there any chance you will be adding that ability with a button / section like there is for "Ports".
Or
Any chance there can be an additional "command" box that will enter switches ~before~ the name of the image is called and then volumes could be mapped that way as well.

Thanks
--Tom

**Comment by felixgborrego** [comment]
As far as I know there is no way to send any arbitrary options through Docker Remote API.
It was already in my TODO list, I'll add a simple ui for volume mapping ASAP.

**Comment by tom472** [comment]
That's great - Can't wait to see that addition.
Awesome app.

**Comment by felixgborrego** [comment]
I released a new version (0.3.0) with support for environment and volumes, let me know if you find something is not working properly.
