### ISSUE TITLE
run environment and volumes variables

### ISSUE THREAD

**Issue by arnobeck** [felixgborrego/docker-ui-chrome-app#14]
Hello,
It would be nice to be able to change the default value for environment variables and volumes on the "run" command.
Thanks

**Comment by felixgborrego** [comment]
Already working on a new version to support Volumes, I'll tackle environment too.

**Comment by felixgborrego** [comment]
I released a new version (0.3.0) with support for environment and volumes, let me know if you find something is not working properly.

**Comment by saggiyogesh** [comment]
Is this include setting up new environment variables ?
