### ISSUE TITLE
Would be nice to support see std/strr from container

### ISSUE THREAD

**Issue by yahuio** [felixgborrego/docker-ui-chrome-app#15]
Currently you can only attach to terminal, and see File system changes in container instances. Would be great if there's a tab for std/err.

**Comment by felixgborrego** [comment]
Thanks for your feedback. I'll see if I can include this in the next release.

**Comment by felixgborrego** [comment]
@yahu577 I misunderstood your comment. The virtual terminal is already a connection to the stdin/stdout/err of the container.
