### ISSUE TITLE
No scroll bar in console, its window width is changed chaotically

### ISSUE THREAD

**Issue by leonty** [felixgborrego/docker-ui-chrome-app#16]
When I scroll inside the console till the end, its window is as wide as the browser window (ever wider and crosses the border on the right). See 1.png.
When I scroll inside the console up, its windows gets shrinked and the text is wrapped. See 2.png.

Would be great to have always same width console window (as wide as the browser) and to have another scroll bar inside the console window.

![1](https://cloud.githubusercontent.com/assets/1595354/9824690/2abcd4c8-58d7-11e5-936c-8b70503c10bd.png)
![2](https://cloud.githubusercontent.com/assets/1595354/9824691/2c87bf0c-58d7-11e5-9cd6-30deb0f4040b.png)

**Comment by felixgborrego** [comment]
Thanks for your feedback, I'm aware of this issue and still trying to get this virtual terminal right. I'll keep an eye on it.
On the other hand, I saw the error before, but now I'm not able to reproduce it, see gif.

![1](http://g.recordit.co/XmQLv57HR4.gif)
