### ISSUE TITLE
Add instructions for docker-machine

### ISSUE THREAD

**Issue by jzer7** [felixgborrego/docker-ui-chrome-app#21]
At least on MacOS, the preferred path is to use docker-machine (instead of boot2docker).  Changes to the documentation on the _Settings_ section would be sufficient.

**Comment by felixgborrego** [comment]
Thanks, I'm going to remove the instructions in the app and just link to the wiki so It's easy to keep the docs up to date.

**Comment by felixgborrego** [comment]
Wiki updated with instructions for docker-machine:
https://github.com/felixgborrego/docker-ui-chrome-app/wiki/Mac-OS-X
