### ISSUE TITLE
Cant Stop the Docker pull

### ISSUE THREAD

**Issue by junejie** [felixgborrego/docker-ui-chrome-app#23]
After selecting the repository i would like to clone. It started to clone.
But when i want to stop the pulling. I cant stop it.

Im using chrome 44, Ubuntu 14.04

**Comment by felixgborrego** [comment]
Hi,
As far as I know there is not way to stop a pull using the Docker Remote API, therefore you can't stop it using the UI.
 I'll take a look to the new version of Docker to see if there is a new way to do it. But for now, I'm sorry, but you can just remove or Garbage collect the pulled images :(

**Comment by felixgborrego** [comment]
I fond an error in the pull, we still can't cancel but the current version is pulling all the tags so it actually takes quite a while. And it's even more annoying because you can cancel :(.
I'll publish in a few days a version that only pull the 'last' tag.
