### ISSUE TITLE
can not connect to my docker daemon

### ISSUE THREAD

**Issue by epiphyllum** [felixgborrego/docker-ui-chrome-app#24]
my docker daemon admin serivce is bound to "-H  tcp://192.168.100.10:1234"

this chrom app for windows can connect to it
but this chrome app in my mac can not connect to it

**Comment by felixgborrego** [comment]
Hi,
Have you try to connect without the app putting the right url in the browser? something like: https://192.168.100.10:1234/_ping ?
You can see more info in https://github.com/felixgborrego/docker-ui-chrome-app/wiki/Mac-OS-X
