### ISSUE TITLE
Container Running List 'name' column would be nice.

### ISSUE THREAD

**Issue by alexrjs** [felixgborrego/docker-ui-chrome-app#25]
Hi,

great extension, I use it on a regular basis. But, isn't there always a but :-), I miss the "name" column in the "Container Running" list. 

I've a bunch of Jenkins docker container running and I can only distinguish between them by the port, even they have "speaking" names.

Would be a nice enhancement.

Thanks and Cheers,
  Alex

PS: A Refresh Icon would be nice too :-)

**Comment by felixgborrego** [comment]
Thanks to your feedback, seems easy to add, I'll release a new version with this as soon as posible.

**Comment by alexrjs** [comment]
Hi,

greatly appreciated… 

Cheers,
  Alex

**Comment by felixgborrego** [comment]
Released

**Comment by alexrjs** [comment]
Many thanks... Great solution... Love it... :-)
