### ISSUE TITLE
Is Swarm supported?

### ISSUE THREAD

**Issue by donaldquixote** [felixgborrego/docker-ui-chrome-app#26]
Apologies for lack of screenshot.

I can point Docker UI to a Swarm master node on the swarm API port (3376), but it seems to only partially work.

The Home page lists version as "swarm/1.0.0 (api: 1.21). There should be three containers, all running, but running containers shows 0. All containers does show 3 as expected.

The Containers page reports "Unable to connect"

The Images page appears to work fine.

I can connect to each swarm node separately, as well as the swarm master on vanilla Docker API port (2376) and everything works as expected (minus unrelated issues already raised in other tickets).

So is Docker swarm supposed to be supported yet, or is it just coincidence that a few bits appear to work already?

**Comment by felixgborrego** [comment]
Hi, personally I haven't try Swarm yet so 'it's a coincidence',  I'll take a look to see if it's easy enough to support, my guess is I need to bump the Docker api version to fix the some incompatibility. 
It's something I definitely like to have!

**Comment by felixgborrego** [comment]
Already released a version with basic support for Swarm ( I'm preparing some more improvements)
It was a issue in the json parser for some new data included in the api for Swarm.

**Comment by donaldquixote** [comment]
Great! Took a quick peek and all seems well. Is there a roadmap for enhancements to Swarm support? I have a few suggestions, but I don't want to add noise to the issue queue if you've already made plans for some of them.

Thanks!

**Comment by felixgborrego** [comment]
@donaldquixote suggestions and ideas are welcome!
Just be aware this is just a side project and I can't really spend as much time as I'd like :(

**Comment by donaldquixote** [comment]
Understood. Thanks for your time-on-the-side :)
