### ISSUE TITLE
It would be useful to see the names of the containers

### ISSUE THREAD

**Issue by mrvini** [felixgborrego/docker-ui-chrome-app#27]
I have 3 web server containers running, it would be nice to see the name of the container.

Thank you for a nice app

**Comment by felixgborrego** [comment]
Hi, @mrvini thanks for your feedback. I think this was already done in the last update
are you talking about the some thing than [this issue](https://github.com/felixgborrego/docker-ui-chrome-app/issues/25) related?

**Comment by mrvini** [comment]
Hi @felixgborrego, 
its strange, I've loaded the recent version from the chrome store and I don't see it. 
FYI, I am running it on ubuntu 14.04

**Comment by felixgborrego** [comment]
@mrvini I'll take a look. You should see it under the Container Id.
![screen shot 2015-12-07 at 09 38 59](https://cloud.githubusercontent.com/assets/650738/11623757/daface66-9cc6-11e5-9148-a2e17e9b878b.png)

**Comment by mrvini** [comment]
@felixgborrego , I apologies , see it now. I was expecting output similar to `docker ps -a`, thus a sep column, and did not see :). Its all good now. closing the issue
