### ISSUE TITLE
Any server statistic (memory/disk/cpu)?

### ISSUE THREAD

**Issue by carloreggiani** [felixgborrego/docker-ui-chrome-app#28]
Great tool!

Is it possible to add any statistic about server load in realtime? I'm using a "remote" docker daemon on a linux server and working on my pc only with the docker client.

Could be usefull to monitor CPU/RAM/HDD on the daemon server.

Carlo

**Comment by felixgborrego** [comment]
@carloreggiani thanks for your feedback. I have the raw data, I'll think about an easy way to include this info in the ui.

**Comment by felixgborrego** [comment]
I'm going to release in a few days a new version with basic support for stats. ref: #35
It'll look like this:
<img width="1126" alt="screen shot 2016-01-12 at 22 08 49" src="https://cloud.githubusercontent.com/assets/650738/12278546/b5b8bb84-b979-11e5-9d20-898c45a7c402.png">

**Comment by carloreggiani** [comment]
Thank you, Felix!
I'm ready to test it :)
