### ISSUE TITLE
Add instructions for docker-machine on Linux

### ISSUE THREAD

**Issue by jaycyb** [felixgborrego/docker-ui-chrome-app#30]
I am using docker-machine on Linux/Ubuntu and couldn't setup the certificates properly. 

The docker-ui-chrome-app works like a charm without https however that breaks docker-machine...

I tried following the steps on the wiki for [OSX](https://github.com/felixgborrego/docker-ui-chrome-app/wiki/Mac-OS-X) and [Linux](https://github.com/felixgborrego/docker-ui-chrome-app/wiki/linux), issue #21 without success.

Specifically this part:

> - First, make Chrome trust in the auto-generated CA. Execute this command to add the new CA to your Certificate Trust Settings in your Keychain:
>   
>    `security add-trusted-cert -k ~/Library/Keychains/login.keychain ~/.docker/machine/certs/ca.pem`
> - Also, you need to add the auto-generated certificate to your Keychain:
>   
>    `security import ~/.docker/machine/certs/key.pem -k ~/Library/Keychains/login.keychain`
>   
>    `security import ~/.docker/machine/certs/cert.pem -k ~/Library/Keychains/login.keychain`

I added those keys to the Gnome keyring application but not sure of the exact command line...

**Comment by felixgborrego** [comment]
@jaycyb I haven't test myself linux and docker-machine yet, but but maybe this could help http://www.korecky.org/?p=855. 

You first will need to generate the p12 file from `key.pem` and `cert.pem` with something like:
openssl pkcs12 -export -out certificate.p12 -inkey key.key -in cert.crt 

I'll try it too as soon as I get access to a Linux machine, let me know if you have any progress.

**Comment by jaycyb** [comment]
thanks @felixgborrego that looks interesting. I will give it a try.
