### ISSUE TITLE
Linking and system variables

### ISSUE THREAD

**Issue by socialdefect** [felixgborrego/docker-ui-chrome-app#31]
Love docker ui but there are still a couple of things that make me have to use the cli; linking containers, setting system variables and port forwards. If these things could be managed from within Docker Ui it would have all important basic docker features and would completely replace the CLI for the average user.

**Comment by felixgborrego** [comment]
There is already basic support for system variables and port forward when starting a new Image. I'll include linking containers as soon as I can.

**Comment by felixgborrego** [comment]
Basic support for linking containers released in version 0.4.2
