### ISSUE TITLE
Link account with https://hub.docker.com/stars/

### ISSUE THREAD

**Issue by pinage404** [felixgborrego/docker-ui-chrome-app#32]
Hello,

First, thanks for this app, this was what i searched.

Is is possible to **link the account** with https://hub.docker.com/stars/ to **get starred containers** and **add** the **star from the app** ?

Thanks for this cool app

**Comment by felixgborrego** [comment]
Thanks for your feedback, I couldn't find any API to get this info.Sso for now I don't see any way to get this data.
