### ISSUE TITLE
Edit container properties

### ISSUE THREAD

**Issue by bdaniel7** [felixgborrego/docker-ui-chrome-app#33]
A very nice enhancement would be to allow the user to edit the container properties, like the command, the environment, working dir, volume mapping.

**Comment by felixgborrego** [comment]
Currently there is is already basic support for system variables, volume mapping and port forward when starting a container from an Image. Do you mean editing this options when restarting a container?, I'm not sure if this is posible but I'll take a look to the api.

**Comment by bdaniel7** [comment]
Ok, where can I edit those variables?
My use case would be:
1. edit a variable
2. start the container
3. if something is not right, stop the container and go to step 1.

**Comment by felixgborrego** [comment]
With the current version,  you can edit these when you are creating a new container from an Image. Not sure if this is what you are looking for:
<img width="619" alt="screen shot 2016-01-04 at 20 16 52" src="https://cloud.githubusercontent.com/assets/650738/12099448/7bd289ae-b320-11e5-9a7a-5ba53f97025b.png">

**Comment by bdaniel7** [comment]
Ok, then I don't have the latest version. 
I don't see that screen in what I have installed (Chrome App Simple Docker UI 0.4.1)

**Comment by bdaniel7** [comment]
So, can we expect a new release on Google Apps?

**Comment by felixgborrego** [comment]
@bdaniel7, sorry maybe I'm not understanding you. With the version you have installed, you should be able to edit Environments when staring a staring a new container from an Image. Go to Images>"Select the image"-> Click Start, and see the Environments.

From you previous use case:
0. Select the Image to start 
1. edit a variable
2. start the container
3. if something is not right, stop the container and go to step ~~1~~ 0.

Maybe you are trying to start an already existing container, I'm not even sure this is posible using the CLI, but it's not posible using the UI. But what you can do is edit the Environments before starting a new container from an existing Image. (See image above)

**Comment by bdaniel7** [comment]
Ah... now I see what you mean..I was only starting containers already created with the CLI (docker-compose).
