### ISSUE TITLE
deploy new containers?

### ISSUE THREAD

**Issue by gavinengel** [felixgborrego/docker-ui-chrome-app#34]
Is it possible for Docker UI to deploy a new container?

**Comment by felixgborrego** [comment]
Not sure if I understood your question. It's posible to start a container from an existing image but you can not create a new Image using the ui yet.

**Comment by gavinengel** [comment]
OK.  This is one big difference between Docker UI and Shipyard Project.  I'd love to be able to replace Shipyard with Docker UI.

By the way, do you have a paid channel for your product?  I'm willing to pay a fee for extra features like the one I mentioned.

**Comment by felixgborrego** [comment]
I'll take a look to Shipyard (I haven't use it myself) and check if this can done through the Remote API.

About a 'paid channel', I don't have but you already make me happy :D. I may add a Donate button in the future. Anyway, sorry for the slow development, It's just a side project I don't really spend too much time on it.
