### ISSUE TITLE
Home and Containers tabs hang for (api 1.17, docker 1.7.1)

### ISSUE THREAD

**Issue by kashyap-parikh** [felixgborrego/docker-ui-chrome-app#37]
I am on docker version 1.7.1 and API v 1.17.
On a VM running ~40 containers the Home and Containers tab take 2+ minutes to load.

Specifically following API spikes CPU usage of docker daemon process

/v1.17/containers/json?all=false&size=true

Removing size returns results instantaneously.

**Comment by felixgborrego** [comment]
Hi thanks for your feedback, I wasn't able to replicate this huge CPU usage/response time (Docker 1.9) so I guess it could be the case that this has been improved in recent Docker version (or my containers doesn't have that many layers). 
Anyway I'm going to use your suggestion and remove `size` in the Container tabs, it definitely will make the ui more responsive. 
About the Home screen not sure what else I can do without removing the Size in the ui, but I'll think about it.

**Comment by felixgborrego** [comment]
I definitely can't replicate this performance issue with Docker 1.9, I'll keep an eye on this one, but I'm afraid next version will not contain any significant change in this regard.
