### ISSUE TITLE
Great, but what about security?

### ISSUE THREAD

**Issue by R0GGER** [felixgborrego/docker-ui-chrome-app#38]
This is a great app! Wow!
But what about security? 

How can I make sure that public_ip:2375 can only used by my own ip/hostname?
OS: Ubuntu 14.04 
Docker: 1.9.1

**Comment by felixgborrego** [comment]
Hi, you are right, on the [wiki for Linux](https://github.com/felixgborrego/docker-ui-chrome-app/wiki/linux) you can see only how to configure it to allow connections from everywhere. I haven't test it myself but here are some options:
- Redefine `DOCKER_OPTS='-H tcp://0.0.0.0:2375` to use accept only connections from your ip.
- Use a similar approach than in Windows/[Macos](https://github.com/felixgborrego/docker-ui-chrome-app/wiki/Mac-OS-X), and keep auth based on certificates enabled (this is the Docker default) and install the certificates in your Chrome. Sorry I haven't done it myself so I'm not sure how it can be done in Ubuntu.

**Comment by R0GGER** [comment]
```
iptables -A INPUT -p tcp --dport 2375 -s 11.222.33.444 -j ACCEPT
iptables -A INPUT -p tcp --dport 2375 -j DROP
```
