### ISSUE TITLE
Support basic auth please

### ISSUE THREAD

**Issue by jhartlep** [felixgborrego/docker-ui-chrome-app#40]
Hey,
I have put my docker remote api behind a nginx reverse proxy (configured via ssl with basic auth).
But this makes Simple Docker UI unable to access the remote api...
When I disable basic auth, I can connect to the api, but I don't want this open without credentials...
Could you please change this?

Best Regards,

**Comment by mgttt** [comment]
I have the same requirement as yours...  losing the basic auth, the app is not able to go production...poor....

**Comment by stedaniels** [comment]
Hi Felix,

Is support for basic auth, or TLS client certificates on your roadmap, or are you open to pull requests?

Cheers,

**Comment by felixgborrego** [comment]
@stedaniels, it wasn't in my roadmap, but I'll evaluate it.
Basic Auth should be simple to implement, I'll give it a try this weekend.
As for TLS client certificates, if Chrome can connect with a installed TLS client, then the app should connect too.

**Comment by felixgborrego** [comment]
I just checked and it's posible to use basic auth just by including the credentials in the url like:

```
http://user:pass@localhost:4242/
```

**Comment by stedaniels** [comment]
Thanks, ill family at the weekend stopped me from getting a chance to explore it.  That should work great for me :-)  I appreciate you testing and confirming.

**Comment by jhartlep** [comment]
Thanks,
I just tested it, and it worked!
