### ISSUE TITLE
connection to swarm cluster fail

### ISSUE THREAD

**Issue by ppiccolo** [felixgborrego/docker-ui-chrome-app#41]
Hi, 

i'm unable to connect to the swarm cluster : Unable to connect to http://swarm-master-ip:4000, is Docker daemon running?

however is possible with standard docker api 

Bye

**Comment by felixgborrego** [comment]
@ppiccolo did you try to connect to this url using the just the browser? it doesn't look like a valid swarm url. Just as an example mine is https://192.168.99.100:3376.
You should use the one returned by `docker-machine env --swarm swarm-master` replacing `tcp` by `https`

**Comment by ppiccolo** [comment]
I'm working without docker-machine, the cluster is deployed over 3 virtual machine over esxi and the swarm standard docker command can connect to the swarm master and replica 
ex:
docker -H tcp://192.168.70.205:4000 info

Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 3
Server Version: swarm/1.1.2
Role: primary
Strategy: spread
Filters: health, port, dependency, affinity, constraint
Nodes: 3
 docker-host-01: 192.168.70.206:2375
  └ Status: Healthy
  └ Containers: 1
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 4.046 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.16.0-30-generic, operatingsystem=Ubuntu 14.04.4 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-03-01T08:43:38Z
 docker-host-02: 192.168.70.207:2375
  └ Status: Healthy
  └ Containers: 1
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 4.046 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.16.0-30-generic, operatingsystem=Ubuntu 14.04.4 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-03-01T08:43:14Z
 docker-host-03: 192.168.70.208:2375
  └ Status: Healthy
  └ Containers: 1
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 4.046 GiB
  └ Labels: executiondriver=native-0.2, kernelversion=3.16.0-30-generic, operatingsystem=Ubuntu 14.04.4 LTS, storagedriver=aufs
  └ Error: (none)
  └ UpdatedAt: 2016-03-01T08:43:32Z
Plugins: 
 Volume: 
 Network: 
Kernel Version: 3.16.0-30-generic
Operating System: linux
Architecture: amd64
CPUs: 12
Total Memory: 12.14 GiB
Name: fb805ecc574b
