### ISSUE TITLE
trying to connect to docekr for mac OSX and it fails

### ISSUE THREAD

**Issue by bgrissin** [felixgborrego/docker-ui-chrome-app#42]
the new docker osx whcih uses docker.local as the xhyve instnace to run docker fails to verify

**Comment by felixgborrego** [comment]
I'm still investigating how to connect, but I haven't found a way to connect from Chrome yet.

**Comment by gabrielmancini** [comment]
run jarkt/docker-remote-api
change the port
enjoy

**Comment by kcampion** [comment]
Thank you @gabrielmancini, it works with this command line:

`# docker run --restart always -p 2376:2375 -v /var/run/docker.sock:/var/run/docker.sock jarkt/docker-remote-api`

**Comment by felixgborrego** [comment]
The native version of SimpleDockerUI for Mac  (still in beta) works fine with Docker for Mac.
https://github.com/felixgborrego/docker-ui-chrome-app/releases
