### ISSUE TITLE
Native Docker socket support

### ISSUE THREAD

**Issue by danielbjornadal** [felixgborrego/docker-ui-chrome-app#44]
Would be nice if the dashboard supported the native docker tcp socket on docker and swarm.

Now, it errors:
"Unable to connect to http://192.168.26.11:4000, is Boot2docker/docker-machine running?"

**Comment by felixgborrego** [comment]
You can use native sockets (and Docker for Mac) using the native SimpleDockerUI for Mac.
https://github.com/felixgborrego/docker-ui-chrome-app/releases
