### ISSUE TITLE
Anoying log scroll on console when only want start a container

### ISSUE THREAD

**Issue by scaamanho** [felixgborrego/docker-ui-chrome-app#45]
On line 225 of `DockerClient.scala` file you use

`val ws = schema + substringAfter(s"$url/containers/$containerId/attach/ws?logs=1&stderr=1&stdout=1&stream=1&stdin=1", "://")`

I supose you use this service to atach container to **docker-ui** container console

here you are using  **logs** flag set to **_true**_ (defaults is false)

This brings all historic logs from the container.
The problem i find here, is getting all log history in containers that generate a great amount of logs, as gitlab container, when i try to start it from **docker-ui** i get stuck for a while until i can press start button.
Could be more usefull manage both functionalities in a diferent way.
- one to atach console to container without log history, as when u attach to a container from command line
- another to visualize logs through service `GET /containers/(id or name)/logs`

Another option is give the posibility of visualize logs or not.

I know you want keep your app simple, so may not be a great idea, in any case just want tell you as a sugestion

Best regards and thanks for your great work

**Comment by felixgborrego** [comment]
Hi, @scaamanho thanks for the feedback. I haven't notice this issue because I can't use the app myself in any production server. But you are right, it's really annoying for long running containers or huge logs.
I'm going to play with your ideas, and see what I can do.

**Comment by felixgborrego** [comment]
Maybe I just can reorder the information of the Tabs, so the "Terminal" is not the default tab and the app dones't need to get the logs by default.

So now will only get 
<img width="966" alt="screen shot 2016-05-03 at 17 36 41" src="https://cloud.githubusercontent.com/assets/650738/14990705/b9167bf2-1155-11e6-91cf-b28151a599b0.png">
@scaamanho what do you think? is it maybe enough?

**Comment by scaamanho** [comment]
its a nice workarround. thanks for your attention

**Comment by felixgborrego** [comment]
Version 0.4.4 include this work around (already in the store)
