### ISSUE TITLE
Home tab of the app not connecting

### ISSUE THREAD

**Issue by adamculp** [felixgborrego/docker-ui-chrome-app#46]
I am on Ubuntu 16.04 Desktop with Docker version 1.11.1. I followed the instructions on the wiki to set up for a system running systemd at https://github.com/felixgborrego/docker-ui-chrome-app/wiki/linux and all seemed to go well. (systemd shows everything running as expected)

When I try http://localhost:2375/_ping in a browser I receive "OK". However, if I drop the ending and simply enter http://localhost:2375 I get a 404 error. (Also tried the machine IP as well as 127.0.0.1)

When I open the Simple Docker UI app the Containers, Images, and Settings tabs all work fine despite the 404 error in the browser and the Home tab.

I'm relatively new to Docker, so not sure what info I can provide you to help figure this out. A web search didn't yield much luck.

NOTE: I am able to install images, and run containers just fine, via CLI or the Simple Docker UI.

**Comment by felixgborrego** [comment]
Thanks for reporting, you are right, there is a parser issue with the new version, I'll release a fix in a few days.

**Comment by felixgborrego** [comment]
Version 0.4.4 should fix this issue (already in the store)

**Comment by adamculp** [comment]
Thank you for all you do. I confirm that it is now fixed.
