### ISSUE TITLE
unable to view containers

### ISSUE THREAD

**Issue by exile259** [felixgborrego/docker-ui-chrome-app#48]
App connects, able to view available images and deploy, but am unable to view running containers

**Comment by felixgborrego** [comment]
I just tested locally with Docker 1.11.0-rc4 (API: 1.23) and it's working.
There may be an incompatibility with a version I haven't test, I'll review it.  
Meanwhile, 
- what is your version? 
- can you update docker?

Also, I'll really appreciate if can you send me the last lines in your Javascript console (mouse right button>Inspect>console tab)[Chrome may need to be in dev mode]

**Comment by exile259** [comment]
docker-io.x86_64                    1.7.1-2.el6                       @epel

according to Yum it's the latest available.

I'm on OSX/Chrome 50 and even with developer mode on I do not get any right
click->inspect options in your app

**Comment by felixgborrego** [comment]
Thanks for taking the time to check it. I tested against 1.7.1 and couldn't find the issue yet. 

Still have a few things I'd like to double check. Meanwhile, maybe you can still help me with this issue,
here you can see how to open the inspector:
http://stackoverflow.com/questions/10257301/where-to-read-console-messages-from-background-js-in-a-chrome-extension   (and Inspect index.html)

**Comment by lukaville** [comment]
I am trying to use UI with Docker Swarm API and also I am unable to view running containers.

Log:
`error: [ContainersPage] Unable to get Metadata  null - Parser error: Obj(ArrayBuffer((Id,Str(083117818e3e145e93cf3d4ca39083208955753158b5a679dfef62422d0a224f)), (Names,Arr(WrappedArray(Str(/frontend/xxx_frontend_1)))), (Image,Str(registry.xxx.com:5000/frontend:prod)), (Command,Str(/usr/bin/runsvdir /etc/service)), (Created,Num(1465248866)), (Status,Str(Up 20 hours)), (Ports,Arr(WrappedArray(Obj(ArrayBuffer((IP,Str(11.11.11.11)), (PrivatePort,Num(443)), (PublicPort,Num(443)), (Type,Str(tcp)))), Obj(ArrayBuffer((IP,Str(11.11.11.11)), (PrivatePort,Num(80)), (PublicPort,Num(80)), (Type,Str(tcp))))))), (SizeRw,Num(0)), (SizeRootFs,Num(0)), (Labels,Obj(ArrayBuffer((com.docker.compose.config-hash,Str(abeaccccc1d6e8fdb78b2d96ed618f69273198f668ff435b0dc754cccb756a1a)), (com.docker.compose.container-number,Str(1)), (com.docker.compose.oneoff,Str(False)), (com.docker.compose.project,Str(xxx)), (com.docker.compose.service,Str(frontend)), (com.docker.compose.version,Str(1.7.0)), (com.docker.swarm.constraints,Str(["node==frontend"])), (com.docker.swarm.id,Str(4ee90cc39202a22427174c78d1dffaf3ced19cccdea2364344526f448fefad6a))))), (NetworkSettings,Obj(ArrayBuffer((Networks,Obj(ArrayBuffer((xxx_default,Obj(ArrayBuffer((IPAMConfig,Null), (Links,Null), (Aliases,Null), (NetworkID,Str()), (EndpointID,Str(9f0240229dd687a6827e1924e6c082e70ca056ae29ba75c57af167513c1dab72)), (Gateway,Str()), (IPAddress,Str(10.0.0.24)), (IPPrefixLen,Num(24)), (IPv6Gateway,Str()), (GlobalIPv6Address,Str()), (GlobalIPv6PrefixLen,Num(0)), (MacAddress,Str(02:42:0a:00:00:18))))))))))))) Key Missing: ImageID
scalajs-opt.js:1215 [dockerClient.ping] return: OK`

`[dockerClient.version] return: {"Version":"swarm/1.2.0","ApiVersion":"1.22","GitCommit":"a6c1f14","GoVersion":"go1.5.4","Os":"linux","Arch":"amd64","KernelVersion":"4.2.0-36-generic","BuildTime":"Wed Apr 13 05:58:31 UTC 2016"}`

**Comment by felixgborrego** [comment]
Thanks @lukaville for your report, I'll investigate it and release a new version as soon as possible.
Looks like `ImageID` is missing in the Container definition in some Docker/Swarm API versions.

**Comment by felixgborrego** [comment]
@lukaville, I released a new version (0.4.8) that may fix the parser issue you reported. 
The JSON parser was expecting the field `ImageID`, but this value is present only on API 1.23+

**Comment by lukaville** [comment]
List of images is working now on API 1.22. Thanks!
