### ISSUE TITLE
use default container ports when possible

### ISSUE THREAD

**Issue by danielzzz** [felixgborrego/docker-ui-chrome-app#55]
hi, I was wondering how are the ports to be mapped chosen? For example if a container exposes "8043" and I choose "all" to be mapped, you (or docker maybe) randomly selects ports on the host, right?

It would be great if the ports were the same as in the container by default (if available), as this would make the container transparent.

maybe related: #52 

cheers, dan

**Comment by felixgborrego** [comment]
Sorry but I don't have a clear answer for you.
Docker UI just uses "-P", as far as I know it tries to auto assign the port defined in "EXPOSE" avoiding port mapping conflict.
