### ISSUE TITLE
How to configure for Docker for Mac Beta, since no certs available under ~/.docker/machine/certs/

### ISSUE THREAD

**Issue by alexrjs** [felixgborrego/docker-ui-chrome-app#57]
Hi,

with the new Docker for Mac Beta, the Documentation for configuring Mac is no longer working... There are no certificates to use... There is no more folder ~/.docker/machine/certs/*

But the docker is available via rest... 
`> curl --unix-socket /var/run/docker.sock http://macix:2376/images/json`
`[{"Id":"sha256:0d409d33b27e47423b049f7f863faa08655a8c901749c2b25b93ca67d01a470d","ParentId":"","RepoTags":["nginx:latest"],"RepoDigests":["nginx@sha256:0fe6413f3e30fcc5920bc8fa769280975b10b1c26721de956e1428b9e2f29d04"],"Created":1464804059,"Size":182786784,"VirtualSize":182786784,"Labels":{}}]`

Any idea how to do the setup to use it with your Simple Docker UI tool?

Cheers,
  Alex

**Comment by felixgborrego** [comment]
Sorry,
For now, there is no way to connect Chrome with Unix-sockets.
The only workaround I can recommend you is using a proxy:
https://github.com/felixgborrego/docker-ui-chrome-app/issues/42

**Comment by felixgborrego** [comment]
You can use The native SimpleDockerUI for Mac. It makes easy to connect with Docker for Mac.

https://github.com/felixgborrego/docker-ui-chrome-app/releases

**Comment by alexrjs** [comment]
Thanks, yes 0.5.3 does work. But the Home Screen has an odd message:



But it works:



And switching is easy



Cheers,
  Alex
