### ISSUE TITLE
link to hub.docker.com seems to be incorrect

### ISSUE THREAD

**Issue by danielzzz** [felixgborrego/docker-ui-chrome-app#59]
hi, I am not sure if you're generating the link to hub.docker.com or it's taken from the image description but it seems to be incorrect.

For example, for vimagick/monit it's:
https://hub.docker.com/search/?q=vimagick/monit&searchfield:=

which doesn't find anything, but when I type the same query in the form the url generated is:
https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=vimagick%2Fmonit&starCount=0

I'm not sure if you could assume it's on the hub and use an url like this one directly:
https://hub.docker.com/r/vimagick/monit/

best, dan

**Comment by ajurasz** [comment]
@danielzzz came across this yesterday, seems like search url changed on docker hub. To make it work again ulr need to be change to
`https://hub.docker.com/search/?isAutomated=0&isOfficial=0&q=vimagick%2Fmonit`
these two parameters `isAutomated` and `isOfficial` indicate that we want to search `All` images on docker hub.

But indeed direct link to an image page would be better. I will check if it will be possible to make appropriate change and will make PR.
