### ISSUE TITLE
Windows instructions needs to add "export" to "DOCKER_TLS=no"

### ISSUE THREAD

**Issue by tohagan** [felixgborrego/docker-ui-chrome-app#6]
According to this ...
- https://github.com/boot2docker/boot2docker/issues/589

I think you should use "export DOCKER_TLS=no" in your profile not just "DOCKER_TLS=no"

But the `export` is missing from this wiki page:
- https://github.com/felixgborrego/docker-ui-chrome-app/wiki/windows

**Comment by felixgborrego** [comment]
Thanks, https://github.com/felixgborrego/docker-ui-chrome-app/wiki/windows updated
