### ISSUE TITLE
Half work with docker 1.7.0

### ISSUE THREAD

**Issue by leonty** [felixgborrego/docker-ui-chrome-app#7]
Shows only the images. For the pages Home and Containers says "Unable to connect".
Environment:
Server: Ubuntu 15.04, Docker 1.7.0
Client: Chrome 43.0.2357.130 m, Simple Docker UI (Beta) 0.1.2

**Comment by felixgborrego** [comment]
Thanks!. 

It was a parsing error. The previous API was using number for representing Boolean (0/1) and the new version 1.7 is returning true/false. I'll release a new version in the following days.

Fixed: https://github.com/felixgborrego/docker-ui-chrome-app/commit/ed83ffca965249a7b40750be509f4ff2c1253ec3
