### ISSUE TITLE
Only partially working on Ubuntu 14.04 with docker 1.13.0

### ISSUE THREAD

**Issue by sneumann** [felixgborrego/docker-ui-chrome-app#70]
Hi, I get the `Unable to connect to unix:///var/run/docker.sock, is Docker daemon running?`

My user is in the docker group:
`uid=1000(xxx) gid=1000(xxx) groups=1000(xxx),4(adm), [...],124(sambashare),999(docker)`

and the socket is accessible by group docker: 
`srw-rw---- 1 root docker 0 Jan 23 16:57 /var/run/docker.sock`

I can pull/start/stop containers from the commandline as that user. 
I can start/stop containers via SimpleDockerUI (!) but still get 
the error message on the welcome screen and not a verified connection 
in the settings tab. Running under sudo gives same result.

This is on Ubuntu 14.04 with docker 1.13.0 and SimpleDockerUI_0.5.4_amd64.deb
Happy to try a few things :-) Yours, Steffen

**Comment by felixgborrego** [comment]
Thanks for reporting, 
I just updated myself to Docker 1.13.0 and I'm getting the same issue (worked for 1.12.x).
Probably an incompatibility in the Docker Remote API for 1.13, will ping you once I have the fix.

**Comment by sneumann** [comment]
Just saying that I am using simple-docker-ui (0.5.5-1) again this year (now on ubuntu 16.04.03 with Docker 17.12.02-ce) in the same course, and everything works smoothly in the preliminary tests. Thanks, yours, Steffen
