### ISSUE TITLE
Howto build the Chromeapp

### ISSUE THREAD

**Issue by zoutepopcorn** [felixgborrego/docker-ui-chrome-app#74]
I tried to build your chromeapp. 

Included the bower    OK
Installing sbt               OK
compiling sbt              NOT OK :(

https://github.com/zoutepopcorn/docker-ui-chrome-app/blob/e533bdfb657c546fcc37ab1918b61883e06a064d/chromeapp/%20README.md

In the dir: 
```
/docker-ui-chrome-app$ sbt compile
```

It compiles. But now the plugin still cant find: scalajs-fastopt.js 

Maybe you can have a look. I dont know scala.js. Maybe we can add a small readme file?

**Comment by felixgborrego** [comment]
Working with `scala.js` can be tricky.
The instructions to compile as an Electron app are here:
https://github.com/felixgborrego/docker-ui-chrome-app/blob/master/README.md

Basically you need to `/docker-ui-chrome-app$ sbt electron/fullOptJS`
