### ISSUE TITLE
Desktop App on Fedora 25

### ISSUE THREAD

**Issue by shanff** [felixgborrego/docker-ui-chrome-app#75]
Using the desktop app on Fedora 25.  Have setup the connection to Docker Remote API on localhost with both IP and .sock.  Both different connections validate separately.  When I save and go "Home", regardless of which connection type i'm using, I get "Unable to connect to http://localhost:2375, is Docker daemon running? Go to Settings"  

selinux is enabled, but not alerting on anything.  The Chrome App worked wonderfully with the same setup.  Any pointers or wait until a newer version?  What can I provide that might help figuring this one out?

**Comment by felixgborrego** [comment]
I haven't tested with Fedora25, but I get similar issues with the version of Docker 1.13.x
Can you tell me what Docker version are you running?  Can you see the list of containers?  Maybe it's related to #70.

**Comment by pinage404** [comment]
I have the same issue on a Debian 8 based distro

```bash
$ docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:44:08 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:44:08 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

On the home tab, i have just the message:
```
Unable to connect to unix:///var/run/docker.sock, is Docker daemon running?
Go to Settings
```

The others tabs "Containers", "Images" and "Settings" work well as usual

**Comment by shanff** [comment]
@felixgborrego , yes, my version is 1.13.0  No containers or other information being shown.  I'm assuming this can be filed as a duplicate of #70 with the understanding that it appears to be distro agnostic.

**Comment by shanff** [comment]
Close it as a duplicate to #70
